### ISSUE TITLE
incorrect punctuation mark order

### ISSUE THREAD

**Issue by emoxam** [morceaudebois/bonjourr.fr#6]
Hello!
Thanks for the job, extenton are awesome!
But why it has "!," After my name ?) 
It looks like "Hello!, Alexander"
But should be "Hello, Alexander!" i think, i tried to fix it by myself but every edit gives me corrupted extension. Can developer fix it ? Or there is the way to fix it by myself ?
Thanks!

**Comment by morceaudebois** [comment]
Hi @emoxam! Sorry we didn't see your issue, you should have posted it to Bonjourr's [extension repository](https://github.com/victrme/Bonjourr), this one is for the website.

Anyway, I'm glad you like Bonjourr! Which language are you using? We just pushed [an update](https://github.com/victrme/Bonjourr/releases/tag/v1.15.6) that fixes this bug in Russian, so maybe that was it?

**Comment by emoxam** [comment]
> Hi @emoxam! Sorry we didn't see your issue, you should have posted it to Bonjourr's [extension repository](https://github.com/victrme/Bonjourr), this one is for the website.
> 
> Anyway, I'm glad you like Bonjourr! Which language are you using? We just pushed [an update](https://github.com/victrme/Bonjourr/releases/tag/v1.15.6) that fixes this bug in Russian, so maybe that was it?

Accidental "!" in russian greetings is about me )
But is update for edge browser is already available ?

**Comment by morceaudebois** [comment]
It should be soon, we've sent the new version to Microsoft and we're waiting for them to approve it. It usually takes a few hours/days

**Comment by emoxam** [comment]
Thanks! Thats great!
